---
title: "Wilcox BoxPlots"
author: "Abdullah Khan"
date: "2025-04-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(openxlsx)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(dplyr)
library(ggsignif)
path <- "/bgfs/ialdiri/Boxplots/" 
```

### Load in excel sheets
```{r}
down.graph <- read.xlsx("/bgfs/ialdiri/Shared VSX2-SOX2 transcription targets-Final-for revision.xlsx", 2)
up.graph <- read.xlsx("/bgfs/ialdiri/Shared VSX2-SOX2 transcription targets-Final-for revision.xlsx", 5)
```
### Split df by samples
```{r}
down.sox2 <- down.graph[,1:3]
down.vsx2 <- down.graph[,4:6]

up.sox2 <- up.graph[,1:3]
up.vsx2 <- up.graph[,4:6]
```
### Change df and names here
```{r}
df <- down.vsx2
newColnames <- c("Sox2 Unique", "Shared Down-Sox2KO", "Vsx2 Unique")
plotName <- "Down_Vsx2KO"
plotTitle <- "Down in Vsx2KO"
```

1. Format with params from above 
2. Convert to long format 
3. Compute wilcox test and extract pvals
```{r}
colnames(df) <- newColnames
# convert to long format to plot
df.long <- df %>%
  pivot_longer(cols = everything(), names_to = "Group", values_to = "Expression_Level")

# Factor to keep order 
df.long$Group <- factor(df.long$Group, levels = c(newColnames[1], newColnames[2], newColnames[3]), ordered = TRUE)


wilcox_paired <- compare_means(Expression_Level ~ Group, data = df.long, method = "wilcox.test", paired = FALSE)
pval <- compare_means(Expression_Level ~ Group, data = df.long, method = "wilcox.test", paired = FALSE)$p.adj

```

### Plot BoxPlot
```{r}
pdf(paste0(path,plotName,".pdf"), width = 4, height = 8)
ggplot(df.long, aes(x = Group, y = Expression_Level, fill = Group)) + 
  geom_boxplot(
                  outlier.shape = NA,
                  notch = T) + 
  coord_cartesian(ylim = c(-3.5,1)) +
  theme_classic() + 
  xlab("") + 
  ylab("Expression Level") + 
  labs(title = paste0(plotTitle, " - Wilcox Ranked Sum Test")) +
  scale_fill_manual(values = c("red3", "blue3", "green3")) +
  theme(legend.position = "none") +
geom_signif(
    comparisons = list(c(newColnames[1], newColnames[2]),
                       c(newColnames[1], newColnames[3]),
                       c(newColnames[2], newColnames[3])),
    annotations = pval,
    tip_length = 0.01,
    y_position = c(0,.5,-.75)
  )
dev.off()
```









